name = "4th Batt Medical Expansion"
prefix = "medex"
author = "Darkness"
mainprefix = "x"

#modname = "{{prefix}}_mods"
#key_name = "{{prefix}}_{{version}}"
#authority = "{{prefix}}_{{version}}"

[files]
include = [
    "mod.cpp",
    "LICENSE.md",
    "4medx_icon.paa",
    "4medx_logo.png"
]

[hemtt.config]
preset = "Hemtt"

[hemtt.launch]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
    "1779063631", # Zeus Enhanced
    "2020940806", # KAT Medical
]

parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
    "-filePatching",
    "J:\\Documents\\Arma 3 - Other Profiles\\Darknessvoid99\\missions\\ammotest.Stratis\\mission.sqm", # Launch into existing Editor Mission - \\ needed
]